version: "3"
services: 
  postgres:
    container_name: postgres-container
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alfred_delivery
    ports: 
      - "5432:5432"
  api:
    container_name: api-container
    image: node:13
    working_dir: /usr/src/api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist/:/usr/src/api/dist
      - ./package.json:/usr/src/api/package.json
    ports: 
      - "3333:3333"
      - "9222:9222"
    
