version: "3"
services: 
  postgres:
    container_name: postgres-container
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alfred_delivery
    ports: 
      - "5432:5432"
  api:
    container_name: api-container
    image: node:13
    working_dir: /usr/src/api
    restart: always
    command: bash -c "npm install && npm run build-docker && npm run knex-docker:migrate:latest && npm run debug"
    environment:
      DB_HOST: postgres-container
    volumes:
      - ./src/:/usr/src/api/src
      - ./package.json:/usr/src/api/package.json
      - ./tsconfig.json:/usr/src/api/tsconfig.json
      - ./tsconfig-build.json:/usr/src/api/tsconfig-build.json
    ports: 
      - "3333:3333"
      - "9222:9222"
    
